export const perguntas = [
  {
    id: 1,
    type: "date",
    question: "Qual sua data de nascimento?",
  },
  {
    id: 2,
    type: "radio",
    question: "Qual a sua raça/cor?",
    options: [
      { label: "Branca", value: "Branca" },
      { label: "Preta", value: "Preta" },
      { label: "Amarela", value: "Amarela" },
      { label: "Parda", value: "Parda" },
      { label: "Indígena", value: "Indígena" },
      { label: "Ignorado", value: "Ignorado" },
    ],
  },
  {
    id: 3,
    type: "radio",
    question: "Onde ocorreu o fato?",
    options: [
      { label: "Bar ou similar", value: "Bar ou similar" },
      { label: "Comércio/Serviços", value: "Comércio/Serviços" },
      { label: "Escola", value: "Escola" },
      { label: "Habitação coletiva", value: "Habitação coletiva" },
      { label: "Indústrias / Construção", value: "Industrias/ construção" },
      { label: "Local de prática esportiva", value: "Local de prática esportiva" },
      { label: "Outro", value: "Outro" },
      { label: "Residência", value: "Residência" },
      { label: "Via pública", value: "Via publica" },
    ],
  },
  {
    id: 4,
    type: "radio",
    question: "Qual a relação com o(a) autor(a)?",
    options: [
      { label: "Conhecido(a)", value: "conhecido(a)" },
      { label: "Cônjuge", value: "cônjuge" },
      { label: "Desconhecido(a)", value: "desconhecido(a)" },
      { label: "Familiar", value: "familiar" },
      { label: "Múltiplas", value: "múltiplas" },
      { label: "Namorado(a)", value: "namorado(a)" },
      { label: "Não informado", value: "não informado" },
    ],
  },
  {
    id: 5,
    type: "radio",
    question: "Qual o sexo do(a) autor(a)?",
    options: [
      { label: "Masculino", value: "1" },
      { label: "Feminino", value: "2" },
      { label: "Ambos os sexos", value: "3" },
      { label: "Ignorado", value: "9" },
    ],
  },
  {
    id: 6,
    type: "radio",
    question: "Já aconteceu outras vezes?",
    options: [
      { label: "Sim", value: "1" },
      { label: "Não", value: "2" },
      { label: "Ignorado", value: "9" },
    ],
  },
  {
    id: 7,
    type: "radio",
    question: "Qual o seu nível de escolaridade?",
    options: [
      { label: "Não alfabetizada", value: "Não alfabetizada" },
      { label: "1ª a 4ª série incompleta do EF", value: "1ª a 4ª série incompleta do EF" },
      { label: "4ª série completa do EF", value: "4ª série completa do EF" },
      { label: "5ª à 8ª série incompleta do EF", value: "5ª à 8ª série incompleta do EF" },
      { label: "Ensino fundamental completo", value: "Ensino fundamental completo" },
      { label: "Ensino médio incompleto", value: "Ensino médio incompleto" },
      { label: "Ensino médio completo", value: "Ensino médio completo" },
      { label: "Educação superior incompleta", value: "Educação superior incompleta" },
      { label: "Educação superior completa", value: "Educação superior completa" },
      { label: "Ignorado ou em branco", value: "Ignorado ou em branco" },
      { label: "Não se aplica", value: "Não se aplica" },
    ],
  },
];
