import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import NavBar from "@/components/shared/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className}  antialiased`}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
